### ISSUE TITLE
wadda ros failed

### ISSUE THREAD

**Issue by Miki-lin** [windzu/pointpillars#1]
wadda ros failed
 
![Screenshot from 2022-12-07 19-24-08](https://user-images.githubusercontent.com/54935281/206167123-f925677c-42d6-45df-ba34-047bbb761351.png)

**Comment by windzu** [comment]
Sorry, I forgot to add this dependency in wadda, I will fix it as soon as possible.  This is the lack of ros msg, which can be installed through apt. 
`sudo apt install ros-xxx-foxglove-msgs`
xxx is the ros version which can be `noetic` or `melodic`

**Comment by Miki-lin** [comment]
> Sorry, I forgot to add this dependency in wadda, I will fix it as soon as possible. This is the lack of ros msg, which can be installed through apt. `sudo apt install ros-xxx-foxglove-msgs` xxx is the ros version which can be `noetic` or `melodic`

I fix it now, thanks!
